version: '3.5'

services:
  boldbi:
   image: syncfusion/boldbi
   restart: always
   ports:
     - 8085:80
   environment:
     - APP_URL=<APP_URL>
     - BOLD_SERVICES_UNLOCK_KEY=<BOLD_SERVICES_UNLOCK_KEY>
     - BOLD_SERVICES_DB_TYPE=<DB_TYPE>
     - BOLD_SERVICES_DB_HOST=<DB_SERVER_NAME>
     - BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB=<POSTGRES_MAINTAINACE_DATABASE>
     - BOLD_SERVICES_DB_USER=<DB_USERNAME>
     - BOLD_SERVICES_DB_PASSWORD=<DB_PASSWORD>
     - BOLD_SERVICES_USER_EMAIL=<USERNAME>
     - BOLD_SERVICES_USER_PASSWORD=<PASSWORD>
   networks:
     - boldbi
   volumes:
     - boldbi_data:/application/app_data

networks:
  boldbi:
  
volumes:
  boldbi_data:
  db_data: