version: '3.5'

services:
  boldbi:
   image: syncfusion/boldbi
   restart: always
   ports:
     - 8085:80
   environment:
     - APP_URL=<APP_URL>
     - BOLD_SERVICES_UNLOCK_KEY=<BOLD_SERVICES_UNLOCK_KEY>
     - BOLD_SERVICES_DB_TYPE=postgresql
     - BOLD_SERVICES_DB_HOST=pgdb
     - BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB=postgres
     - BOLD_SERVICES_DB_USER=postgres
     - BOLD_SERVICES_DB_PASSWORD=Admin@123
     - BOLD_SERVICES_USER_EMAIL=demo@boldbi.com
     - BOLD_SERVICES_USER_PASSWORD=Admin@123
   networks:
     - boldbi
   volumes:
     - boldbi_data:/application/app_data
    
  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Admin@123
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - boldbi

networks:
  boldbi:
  
volumes:
  boldbi_data:
  db_data:
